stages:
  - test

test-centos7:
  image: centos:7
  stage: test
  before_script:
    - yum install -q -y epel-release
    - yum install -q -y gcc gcc-c++ git lua-devel luajit luajit-devel luarocks make m4 openssl-devel
    - luarocks install lua-requests
    - luarocks install process
    - luarocks install lbase64
    - luarocks install luaunit
    - luarocks install inspect
  script:
    - luajit test/run-test.lua -v -p test_firefox
