notifications:
  webhooks:
    - https://webhook.commit-email.info/

dist: trusty

sudo: required

matrix:
  include:
    - os: osx
      addons:
        firefox: latest-esr
      install:
        - brew update > /dev/null
        - brew bundle
        - sudo -H luarocks install luarocks-fetch-gitrec
        - LUAROCKS="sudo -H luarocks --tree=$(brew --prefix) --lua-dir=$(brew --prefix luajit)"
        - VERSION=$(grep VERSION web-driver.lua | sed -e 's/.*"\(.*\)"/\1/g')
        - cp web-driver.rockspec web-driver-${VERSION}-0.rockspec
        - ${LUAROCKS} make web-driver-${VERSION}-0.rockspec
            CRYPTO_DIR=$(brew --prefix openssl)
            OPENSSL_DIR=$(brew --prefix openssl)
        - rm -rf web-driver.lua web-driver
        - ${LUAROCKS} install luaunit
      script:
        - luajit test/run-test.lua -v
        - ps axuwww | grep geckodriver
        - curl -v https://clear-code.gitlab.io/lua-web-driver/
        - luajit examples/crawl.lua https://clear-code.gitlab.io/lua-web-driver/
