notifications:
  webhooks:
    - https://webhook.commit-email.info/

sudo: required

matrix:
  include:
    - os: osx
      osx_image: xcode10.2
      addons:
        firefox: latest-esr
        homebrew:
          brewfile: true
      install:
        - LUAROCKS="sudo -H luarocks --tree=$(brew --prefix) --lua-dir=$(brew --prefix luajit)"
        - ${LUAROCKS} install luarocks-fetch-gitrec
        - VERSION=$(grep VERSION web-driver.lua | sed -e 's/.*"\(.*\)"/\1/g')
        - cp web-driver.rockspec web-driver-${VERSION}-0.rockspec
        - ${LUAROCKS} make web-driver-${VERSION}-0.rockspec
            CRYPTO_DIR=$(brew --prefix openssl)
            OPENSSL_DIR=$(brew --prefix openssl)
        - rm -rf web-driver.lua web-driver
        - ${LUAROCKS} install luaunit
      script:
        - luajit test/run-test.lua -v
        - luajit examples/get-text-of-element.lua
        - luajit examples/crawl.lua https://lua-web-driver.gitlab.io/lua-web-driver/
