notifications:
  webhooks:
    - https://webhook.commit-email.info/

dist: trusty

sudo: required

matrix:
  include:
    - os: osx
      env:
        GECKODRIVER_VERSION: 0.21.0
      addons:
        firefox: latest-esr
      install:
        - brew update > /dev/null
        - brew bundle
        - curl -L -O https://github.com/mozilla/geckodriver/releases/download/v${GECKODRIVER_VERSION}/geckodriver-v${GECKODRIVER_VERSION}-macos.tar.gz
        - tar xf geckodriver-v${GECKODRIVER_VERSION}-macos.tar.gz -C /usr/local/bin
        - chmod +x /usr/local/bin/geckodriver
        - geckodriver --version
        - ruby -v
        - luarocks --help
        - luarocks config
        - luarocks --lua-dir=$(brew --prefix luajit) config
        - sudo luarocks config
        - sudo luarocks --lua-dir=$(brew --prefix luajit) config
        - luarocks path --bin
        - env
        - echo sudo luarocks --lua-dir=$(brew --prefix luajit) install lua-requests
        - sudo luarocks --lua-dir=$(brew --prefix luajit) install lua-requests
            CRYPTO_DIR=$(brew --prefix openssl)
            OPENSSL_DIR=$(brew --prefix openssl)
        - sudo luarocks --lua-dir=$(brew --prefix luajit) install luautf8
        - sudo luarocks --lua-dir=$(brew --prefix luajit) install process
        - sudo luarocks --lua-dir=$(brew --prefix luajit) install lbase64
        - sudo luarocks --lua-dir=$(brew --prefix luajit) install luaunit
        - sudo luarocks --lua-dir=$(brew --prefix luajit) install inspect
      script:
        - luajit test/run-test.lua
