title: LuaWebDriver
markdown: kramdown
highlighter: rouge
version: 0.1.1
release_date: 2018-11-01
copyright_year: 2018
geckodriver_version: 0.23.0

exclude:
  - "Rakefile"
  - "Gemfile"
  - "Gemfile.lock"

description:
  en: This is a browser automation library using WebDriver API
  ja: WebDriverAPIを使ったブラウザ自動操作ライブラリー

kramdown:
  input: GFM
  smart_quotes: ["apos", "apos", "quot", "quot"]

baseurl: "/lua-web-driver"

sass:
  sass_dir: assets/stylesheets

defaults:
  - scope:
      path: "ja"
    values:
      path_prefix: /ja/
      layout: "base"
      language: ja
      country: JP
  - scope:
      path: ""
    values:
      path_prefix: /
      layout: "base"
      language: en
      country: US
